# Generated by Django 5.2.5 on 2025-09-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorysection",
            name="subheading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
